### ISSUE TITLE
How can I control the font size of the top / bottom bar ?

### ISSUE THREAD

**Issue by Chaiavi** [strayge/FmanActionBar#4]
I assume the control is done via theme.css

Which CSS property controls it ?
Maybe that can also be added to the readme.md ?

**Comment by strayge** [comment]
Not sure that it possible via `css`.

You can edit default `styles.qss` or install [FmanAlternativeColors](https://github.com/strayge/FmanAlternativeColors) and create / edit theme.

This work for me
```css
NewMainWidget QPushButton {
    color: #0000ff;
    font-size: 15pt;
    background-color: #ff0000;
}
```
![image](https://user-images.githubusercontent.com/2664578/129866744-6e8336e5-b6bf-4828-ad1f-8f377883aca1.png)
